version: '3.4'

services:
  catalog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    depends_on: 
      - inventory
    environment: 
      INVENTORY_HOST: inventory
      INVENTORY_PORT: 8080

  inventory:
    image: fsteccanella/academy-inventoryservice:go