version: '3.4'

services:
  catalog:
    build:
      context: ./catalogService
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment: 
      INVENTORY_HOST: inventory-java
      INVENTORY_PORT: 8080

  inventory-go:
    build:
      context: ./inventoryServiceGo
      dockerfile: Dockerfile
  
  inventory-java:
    build:
      context: ./inventoryServiceJava
      dockerfile: Dockerfile